name: Basic CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///:memory:"
      ELASTICSEARCH_URL: http://localhost:9200
      ES_SONG_INDEX_NAME: songs-test
      ES_ARTIST_INDEX_NAME: artists-test

    services:
      elasticsearch:
        image: opensearchproject/opensearch:2.6.0
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          plugins.security.disabled: "true"
          bootstrap.memory_lock: "true"
          OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
        options: >-
          --health-cmd="curl -s http://localhost:9200 | grep -q '\"cluster_name\"'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check that it builds
        run: |
          python -c "import server"

      - name: Run Pytest
        run: pytest
